kind = "web"
previewPath = "/"
title = "Eggpoint"
version = "1.0.0"
id = "artifacts/eggpoint"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21099

[services.development]
run = "pnpm --filter @workspace/eggpoint run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/eggpoint", "run", "build" ]
publicDir = "artifacts/eggpoint/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21099"
BASE_PATH = "/"
